language: shell
install:
    # Download clitest
    - curl -sOL https://raw.githubusercontent.com/aureliojargas/clitest/master/clitest
    - chmod +x clitest
    - mv clitest ~/bin
script:
    - shellcheck txt2regex.sh
    - clitest cmdline.md
