language: python
addons:
  apt:
    packages:
      - shellcheck
      # shfmt is already available
script:
  - make check
  - make test-bash
  - make test-regex

  # The repository must remain unchanged after the checks
  - git diff
  - git diff-index --exit-code HEAD
